### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by jovany-wang** [distkv-project/drpc#130]
- [x] Use `Stub` instead of `Proxy` as a client stub name.
- [x] Update the example in README.md.
- [x] Remove `setInterfaceClass` API.

- [x] Fix the red warning about slfj:
![image](https://user-images.githubusercontent.com/19473861/96255180-1049ca00-0fe9-11eb-8a6a-f4619af81287.png)

**Comment by kairbon** [comment]
DRPC's internal logs will be printed through the logging framework in your project. So you need add log framework to your project.
