### ISSUE TITLE
Add 'needOrder' options temporary.

### ISSUE THREAD

**Issue by zhengrenjie** [distkv-project/drpc#57]

**Comment by jovany-wang** [comment]
1. The option should be named `sequential`.
2. It should be off by default.

**Comment by jovany-wang** [comment]
@zhengrenjie @MrKingHH @senyer @MrKingHH  cc

**Comment by zhengrenjie** [comment]
This option must be a client-side option, but server is which side actually handles it.
So I suppose that this option might be attached with 'Request' to transfer from client to server. In that way, this option is not a config setting but an argument of 'Request', and then, it is more like the 'Session' concept.
Moreover, as this option is rarely should be 'true' all the way,  I wander shall & how we handle this option.
@jovany-wang @senyer

**Comment by jovany-wang** [comment]
This is done in #100 by @kairbon
