### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zhengrenjie** [distkv-project/drpc#68]
![image](https://user-images.githubusercontent.com/16499361/71317244-0cc4df80-24b9-11ea-8a8a-bee2cf0677a8.png)
![image](https://user-images.githubusercontent.com/16499361/71317245-10586680-24b9-11ea-8764-2adeb65597e8.png)

**Comment by senyer** [comment]
Fix.
---------
Reason：
When I ran Dst's multi-threaded test, the child thread was not hung. Then, the child thread was asynchronous and executed instantaneously. This caused the main thread to run and the child thread to run. After the main thread runs, the client is closed, which causes the netty channel to be closed. This causes the child thread to report a ChannelCloseException. Eventually, when drpc returns a response, an exception occurs and the exception is caught. The program directly returns to the AsyncResponse object, and the forced conversion fails.

**Comment by senyer** [comment]
Btw, all in all, I think that the return of drpc is also problematic and needs to be adjusted, otherwise the caller is prone to problems. @zhengrenjie @jovany-wang

**Comment by jovany-wang** [comment]
> problems

Thanks, agree with you totally.

**Comment by jovany-wang** [comment]
Please add the brief for this issue, thanks.

**Comment by jovany-wang** [comment]
done
